#!/usr/bin/env bash

echo " deploy s3 bucket using CloudFormation"
aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--stack-name s3-bucket-stack \
--region ap-south-2 \