#!/usr/bin/env bash
# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
# create bucket name
echo "+++++ delete bucket ++++++ "
if [ -z "$1" ]; then
  echo "There is need to be a bucket name. ./bucket my-bucket-name "
  exit 1
fi
  
aws s3api delete-bucket --bucket "$1"