#!/usr/bin/env bash#!/usr/bin/env bash

echo "+++++ sync ++++++ "

set -e
if [ -z "$1" ]; then
  echo "There is need to be a bucket name. ./bucket my-bucket-name "
  exit 1
fi
if [ -z "$2" ]; then
  echo "There is need to be a fileName"
  exit 1
fi

BUCKET_NAME=$1
FILE_NAME_PREFIX=$2

OUTPUT_DIR="temp/s3_bash"
rm -r $OUTPUT_DIR
mkdir -p $OUTPUT_DIR

NUM_FILES=$((RANDOM % 100 + 1))
# Loop through all files in the current directory
for ((i=1; i<=NUM_FILES; i++)); do
    # Generate a random file name
    FILE_NAME="$OUTPUT_DIR/$FILE_NAME_PREFIX${i}.txt"
    # Generate a random content for the file
    CONTENT="This is a random file content ${RANDOM}"
    # Write the content to the file
    echo $CONTENT > $FILE_NAME
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files/